name: Publish to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-server:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Compose Deploy
        run: /usr/bin/docker compose up -d